// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADOzyQ0xliwf8pIdWd6oEnQgzQpAIPArA',
    appId: '1:450260455796:web:f0bdae74b93e4c7a8d9c21',
    messagingSenderId: '450260455796',
    projectId: 'roommatefinder-4e42b',
    authDomain: 'roommatefinder-4e42b.firebaseapp.com',
    storageBucket: 'roommatefinder-4e42b.appspot.com',
    measurementId: 'G-P2TPK467M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfP03_XvOxWWE2qwhjsQ2wAE4W6yUbow',
    appId: '1:450260455796:android:f37d5d40884e36d08d9c21',
    messagingSenderId: '450260455796',
    projectId: 'roommatefinder-4e42b',
    storageBucket: 'roommatefinder-4e42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsqvEY41JeMV11W3_aLq0ghZGCvOvAaxc',
    appId: '1:450260455796:ios:da4f5295f697a4ab8d9c21',
    messagingSenderId: '450260455796',
    projectId: 'roommatefinder-4e42b',
    storageBucket: 'roommatefinder-4e42b.appspot.com',
    iosClientId: '450260455796-bhs9bev1009gttaeqvh096e66qafr4tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.roommatefinder',
  );
}
